/*
 * DeleteAreaDialog.java
 *
 * Created on 23. Juli 2007, 14:30
 */

package todo.dialog;

import todo.dbcon.DB_ToDo_Connect;
import java.sql.*;
/**
 *
 * @author  Marcus Hertel
 */
public class DeleteAreaDialog extends javax.swing.JDialog {
    
    private static int areaID = 0;
    private static String areaName = "";
    private static String areaDescription = "";  
    private Connection con;
    
    /** Creates new form DeleteAreaDialog */
    public DeleteAreaDialog(java.awt.Frame parent, boolean modal,
                            int areaID, String areaName, String areaDescription) {
        super(parent, modal);
        this.areaID = areaID;
        this.areaName = areaName;
        this.areaDescription = areaDescription;
        initComponents();
        setTitle("Bereich " + areaName + " löschen?");
        jLabelArea.setText(areaName);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelArea = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCancel.setText("Nein");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jButtonOk.setText("Ja");
        jButtonOk.setActionCommand("jbutton1");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("    wirklich löschen?");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 140, 20));

        jLabelArea.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelArea.setText("Fehler");
        jPanel1.add(jLabelArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 160, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Möchten Sie die Kategorie");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 190, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 260, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        deleteArea(areaID);
        setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteAreaDialog(new javax.swing.JFrame(), true,
                        areaID, areaName, areaDescription).setVisible(true);
            }
        });
    }
    
    public void deleteArea(int areaID) {
        DB_ToDo_Connect dbCon = new DB_ToDo_Connect();
        dbCon.openDB();
        con = dbCon.getCon();
        try {
            Statement stmt = con.createStatement();
            String sql = "DELETE FROM Bereich WHERE BereichID=" + areaID;
            stmt.executeUpdate(sql);
            stmt.close();
        }
        catch(Exception e) {
            System.out.println(e.toString()); 
            System.exit(1); 
        }
        dbCon.closeDB(con);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelArea;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
