/*
 * DeleteTodoDialog.java
 *
 * Created on 10. Januar 2007, 06:12
 */

package todo.dialog;

import todo.dbcon.DB_ToDo_Connect;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author  Marcus Hertel
 */
public class DeleteTodoDialog extends javax.swing.JDialog {
    
    private static int todoID = 0;
    private static String cat = "";
    private static String topic = "";
    private static String area = "";
    private Connection con;
    /** Creates new form DeleteTodoDialog */
    public DeleteTodoDialog(java.awt.Frame parent, boolean modal, int todoID, 
                                String cat, String topic, String area) {
        super(parent, modal);
        this.todoID = todoID;
        this.cat = cat;
        this.topic = topic;
        this.area = area;
        initComponents();
        setTitle("Element " + cat + " löschen?");
        jLabelTodo.setText(cat + " - " + area + " - " + topic);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelTodo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonOk.setText("Ja");
        jButtonOk.setActionCommand("jbutton1");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jButtonCancel.setText("Nein");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("    wirklich löschen?");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 140, 20));

        jLabelTodo.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelTodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTodo.setText("Fehler");
        jPanel1.add(jLabelTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 330, 20));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Möchten Sie diesen Eintrag");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 190, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 390, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        deleteElement(todoID);
        setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed
    
    public void deleteElement(int todoID) {
        DB_ToDo_Connect dbCon = new DB_ToDo_Connect();
        dbCon.openDB();
        con = dbCon.getCon();
        try {
            Statement stmt = con.createStatement();
            String sql = "DELETE FROM Protokollelement WHERE ToDoID=" + todoID;
            stmt.executeUpdate(sql);
            stmt.close();
        }
        catch(Exception ex) {
            Logger.getLogger(DeleteTodoDialog.class.getName()).log(Level.SEVERE, null, ex);
            System.exit(1); 
        }
        dbCon.closeDB(con);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTodo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
