/**
 * This file is part of 'Todo Application'
 * 
 * @see			http://www.konzept-e.de/
 * @copyright	2006-2011 Konzept-e für Bildung und Soziales GmbH
 * @author		Marcus Hertel, Sven Skrabal
 * @license		LGPL - http://www.gnu.org/licenses/lgpl.html
 * 
 */

package todo.tab;

import todo.util.MyCellRenderer;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import todo.entity.Meeting;
import todo.entity.Memo;
import todo.entity.Todo;
import todo.dialog.TodoNoteDialog;
import todo.gui.MainGui;
import todo.tablemodel.SearchResultTableModel;

public class SearchResultTab extends javax.swing.JPanel
{
	SearchResultTableModel searchResult;
	MainGui mainGui;

	/** Creates new form SearchResultTab */
	public SearchResultTab(SearchResultTableModel searchResult, String searchTerm, MainGui mainGui)
	{
		this.searchResult = searchResult;
		this.mainGui = mainGui;
		initComponents();

		jLabel1.setText("Suchergebnis für '" + searchTerm + "'");
		
		for (int i = 0; i < searchResult.getRowCount(); i++)
		{
			jTable1.setRowHeight(i, searchResult.getRowHeight(i));
		}

		jTable1.getRowSorter().toggleSortOrder(0);
		jTable1.getRowSorter().toggleSortOrder(0);

		jTable1.setDefaultRenderer(Object.class, new MyCellRenderer());
		jTable1.getColumnModel().getColumn(0).setPreferredWidth(70);
		jTable1.getColumnModel().getColumn(1).setPreferredWidth(900);
		jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);

		jTable1.addMouseListener(new MouseAdapter()
		{
			@Override
			public void mouseClicked(MouseEvent e)
			{
				if (e.getClickCount() == 2)
				{
					openElement(jTable1.getSelectedRow());
				}
			}
		});
	}

	private void openElement(int rowIndex)
	{
		Class classType = (Class) jTable1.getValueAt(rowIndex, -2);

		if (classType == Todo.class)
		{
			JPanel newTab = new DefaultScrollTab(new TodoTab(false, (Integer) jTable1.getValueAt(rowIndex, -1), 0, mainGui));
			mainGui.addNewTab(newTab, "Protokollelement bearbeiten");
		}
		else if (classType == Meeting.class)
		{			
			JPanel newTab = new DefaultScrollTab(new MeetingTab(false, (Integer) jTable1.getValueAt(rowIndex, -1), mainGui));
			mainGui.addNewTab(newTab, "Sitzung bearbeiten");
		}
		else if (classType == Memo.class)
		{
			TodoNoteDialog.showMemoPopup((Integer) jTable1.getValueAt(rowIndex, -1));
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(searchResult);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("- kein Text -");

        jButton1.setText("Element bearbeiten");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	openElement(jTable1.getSelectedRow());
}//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
