/*
 * DeleteMeetingDialog.java
 *
 * Created on 9. Januar 2007, 23:41
 */

package todo.dialog;

import todo.dbcon.DB_ToDo_Connect;
import java.sql.*;
/**
 *
 * @author  Marcus Hertel
 */
public class DeleteMeetingDialog extends javax.swing.JDialog {
    
    private static int meetingID;
    private static String meetingType;
    private static String date;
    private static String place;
    private Connection con;    
    /** Creates new form DeleteMeetingDialog */
    public DeleteMeetingDialog(java.awt.Frame parent, boolean modal,
                                int meetingID, String meetingType, String date,
                                String place) {
        super(parent, modal);
        this.meetingID = meetingID;
        this.meetingType = meetingType;
        this.date = date;
        this.place = place;
        initComponents();
        setTitle("Sitzung " + meetingType + " löschen?");
        jLabelMeetingType.setText(meetingType);
        jLabelDate.setText("Datum:  " + date);
        jLabelPlace.setText("Ort:   " + place);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelPlace = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelMeetingType = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonOk.setText("Ja");
        jButtonOk.setActionCommand("jbutton1");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jButtonCancel.setText("Nein");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("    wirklich löschen?");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 140, 20));

        jLabelPlace.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelPlace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlace.setText("Fehler");
        jPanel1.add(jLabelPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 160, 20));

        jLabelDate.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDate.setText("Fehler");
        jPanel1.add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 160, 20));

        jLabelMeetingType.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelMeetingType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMeetingType.setText("Fehler");
        jPanel1.add(jLabelMeetingType, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 160, 20));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Möchten Sie die Sitzung");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 300, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        deleteMeeting(meetingID);
        setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteMeetingDialog(new javax.swing.JFrame(), true, 
                        meetingID, meetingType, date, place).setVisible(true);
            }
        });
    }
    
    public void deleteMeeting(int meetingID) {
        DB_ToDo_Connect dbCon = new DB_ToDo_Connect();
        dbCon.openDB();
        con = dbCon.getCon();
        try {
            Statement stmt = con.createStatement();
            String sql = "DELETE FROM Sitzungsdaten WHERE SitzungsdatenID=" + meetingID;
            stmt.executeUpdate(sql);
            stmt.close();
        }
        catch(Exception e) {
            System.out.println(e.toString()); 
            System.exit(1); 
        }
        dbCon.closeDB(con);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelMeetingType;
    private javax.swing.JLabel jLabelPlace;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
