/*
 * CategoryGUI.java
 *
 * Created on 30. Dezember 2006, 20:57
 */

package todo.gui;

import todo.subgui.CategorySubGUI;
import todo.dialog.DeleteCategoryDialog;
import todo.tablemodel.CategoryTableModel;

/**
 *
 * @author  Marcus Hertel
 */
public class CategoryGUI extends javax.swing.JFrame {
    
    private static CategoryGUI catGUI = new CategoryGUI();
    /** Creates new form CategoryGUI */
    public CategoryGUI() {
        initComponents();
        jTable1.setAutoCreateRowSorter(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNewInstitution = new javax.swing.JButton();
        jButtonEditInstitution = new javax.swing.JButton();
        jButtonDeleteInstitution = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNewInstitution.setText("Neu...");
        jButtonNewInstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewInstitutionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNewInstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButtonEditInstitution.setText("Bearbeiten...");
        jButtonEditInstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditInstitutionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditInstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jButtonDeleteInstitution.setText("Löschen");
        jButtonDeleteInstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteInstitutionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeleteInstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 40));

        jTable1.setModel(new CategoryTableModel());
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 470, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if(evt.WINDOW_GAINED_FOCUS != 1) {
            jTable1.setModel(new CategoryTableModel());
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButtonDeleteInstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteInstitutionActionPerformed
        if(jTable1.getSelectedRow() != -1) {
            Object catID = jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            Object catName = jTable1.getValueAt(jTable1.getSelectedRow(), 1);
            Object catDescription = jTable1.getValueAt(jTable1.getSelectedRow(), 2);
            Integer temp = new Integer(String.valueOf(catID));
            int cID = temp.intValue();
            if(catName != null) {
                DeleteCategoryDialog delCat = new DeleteCategoryDialog(catGUI, true, 
                                                    cID, String.valueOf(catName),
                                                    String.valueOf(catDescription));
            delCat.setVisible(true);
            }
        }  
    }//GEN-LAST:event_jButtonDeleteInstitutionActionPerformed

    private void jButtonEditInstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditInstitutionActionPerformed
        if(jTable1.getSelectedRow() != -1) {
            Object catID = jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            Object catName = jTable1.getValueAt(jTable1.getSelectedRow(), 1);
            Object catDescription = jTable1.getValueAt(jTable1.getSelectedRow(), 2);
            Integer temp = new Integer(String.valueOf(catID));
            int cID = temp.intValue();
            if(catName != null) {
                CategorySubGUI newCat = new CategorySubGUI(1, cID, 
                        String.valueOf(catName), String.valueOf(catDescription));
                newCat.setVisible(true);
            }
         }
    }//GEN-LAST:event_jButtonEditInstitutionActionPerformed

    private void jButtonNewInstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewInstitutionActionPerformed
        int catID = 0;
        String catName = "";
        String catDescription = "";
        CategorySubGUI newCat = new CategorySubGUI(0, catID, catName, catDescription);
        newCat.setVisible(true);
    }//GEN-LAST:event_jButtonNewInstitutionActionPerformed
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryGUI().setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteInstitution;
    private javax.swing.JButton jButtonEditInstitution;
    private javax.swing.JButton jButtonNewInstitution;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
