/*
 * InstitutionGUI.java
 *
 * Created on 29. Dezember 2006, 18:17
 */

package todo.gui;

import todo.subgui.InstitutionSubGUI;
import todo.dialog.DeleteInstitutionDialog;
import todo.tablemodel.InstitutionTableModel;

/**
 *
 * @author  Marcus Hertel
 */
public class InstitutionGUI extends javax.swing.JFrame {
    
    private static InstitutionGUI instGUI = new InstitutionGUI();
    /** Creates new form InstitutionGUI */
    public InstitutionGUI() {
        initComponents();
        jTable1.setAutoCreateRowSorter(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNewInstitution = new javax.swing.JButton();
        jButtonEditInstitution = new javax.swing.JButton();
        jButtonDeleteInstitution = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNewInstitution.setText("Neu...");
        jButtonNewInstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewInstitutionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNewInstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButtonEditInstitution.setText("Bearbeiten...");
        jButtonEditInstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditInstitutionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditInstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jButtonDeleteInstitution.setText("Löschen");
        jButtonDeleteInstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteInstitutionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeleteInstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 40));

        jTable1.setModel(new InstitutionTableModel());
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 470, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteInstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteInstitutionActionPerformed
        if(jTable1.getSelectedRow() != -1) {
            Object institution = jTable1.getValueAt(jTable1.getSelectedRow(), 1);
            Object institutionID = jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            Integer temp = new Integer(String.valueOf(institutionID));
            int instID = temp.intValue();
            if(institution != null) {
                DeleteInstitutionDialog delInst = new DeleteInstitutionDialog(instGUI, true, 
                                                    instID, String.valueOf(institution));
            delInst.setVisible(true);
            }
        }  
    }//GEN-LAST:event_jButtonDeleteInstitutionActionPerformed

    private void jButtonEditInstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditInstitutionActionPerformed
        if(jTable1.getSelectedRow() != -1) {
            Object institution = jTable1.getValueAt(jTable1.getSelectedRow(), 1);
            Object institutionID = jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            Integer temp = new Integer(String.valueOf(institutionID));
            int instID = temp.intValue();
            if(institution != null) {
                InstitutionSubGUI newInst = new InstitutionSubGUI(1, instID, 
                        String.valueOf(institution));
                newInst.setVisible(true);
            }
         }
    }//GEN-LAST:event_jButtonEditInstitutionActionPerformed

    private void jButtonNewInstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewInstitutionActionPerformed
        String institution = "";
        int institutionID = 0;
        InstitutionSubGUI newInst = new InstitutionSubGUI(0, institutionID, institution);
        newInst.setVisible(true);
    }//GEN-LAST:event_jButtonNewInstitutionActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if(evt.WINDOW_GAINED_FOCUS != 1) {
            jTable1.setModel(new InstitutionTableModel());
        }
    }//GEN-LAST:event_formWindowGainedFocus
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                instGUI.setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteInstitution;
    private javax.swing.JButton jButtonEditInstitution;
    private javax.swing.JButton jButtonNewInstitution;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
