/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TopicGUI.java
 *
 * Created on 29.05.2009, 14:32:00
 */

package todo.gui;

import todo.subgui.TopicSubGUI;
import todo.dialog.DeleteTopicDialog;
import todo.tablemodel.TopicTableModel;

/**
 *
 * @author hertel
 */
public class TopicGUI extends javax.swing.JFrame {

    private static TopicGUI topicGUI = new TopicGUI();
    /** Creates new form TopicGUI */
    public TopicGUI() {
        initComponents();
        jTable1.setAutoCreateRowSorter(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNewTopic = new javax.swing.JButton();
        jButtonEditTopic = new javax.swing.JButton();
        jButtonDeleteTopic = new javax.swing.JButton();
        jLabelTopic = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Themen verwalten");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNewTopic.setText("Neu...");
        jButtonNewTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewTopicActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNewTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jButtonEditTopic.setText("Bearbeiten...");
        jButtonEditTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditTopicActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jButtonDeleteTopic.setText("Löschen");
        jButtonDeleteTopic.setEnabled(false);
        jButtonDeleteTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteTopicActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeleteTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabelTopic.setBorder(javax.swing.BorderFactory.createTitledBorder("Thema"));
        jPanel1.add(jLabelTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 60));

        jTable1.setModel(new TopicTableModel());
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 470, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewTopicActionPerformed
        int topicID = 0;
        String name = "";
        String description = "";
        TopicSubGUI newTopic = new TopicSubGUI(0, topicID, name, description);
        newTopic.setVisible(true);
}//GEN-LAST:event_jButtonNewTopicActionPerformed

    private void jButtonEditTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditTopicActionPerformed
        if(jTable1.getSelectedRow() != -1) {
            Object TopicID = jTable1.getValueAt(jTable1.getSelectedRow(), -1);
            String name = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            String description = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 1);
            Integer temp = new Integer(String.valueOf(TopicID));
            int tID = temp.intValue();
            if(name != null) {
                TopicSubGUI newTopic = new TopicSubGUI(1, tID, name, description);
                newTopic.setVisible(true);
            }
        }
}//GEN-LAST:event_jButtonEditTopicActionPerformed

    private void jButtonDeleteTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteTopicActionPerformed
        if(jTable1.getSelectedRow() != -1) {
            Object TopicID = jTable1.getValueAt(jTable1.getSelectedRow(), -1);
            Object name = jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            Object description = jTable1.getValueAt(jTable1.getSelectedRow(), 1);
            Integer temp = new Integer(String.valueOf(TopicID));
            int tID = temp.intValue();
            if(name != null) {
                DeleteTopicDialog delTopic = new DeleteTopicDialog(topicGUI, true,
                        tID, String.valueOf(name),
                        String.valueOf(description));
                delTopic.setVisible(true);
            }
        }
}//GEN-LAST:event_jButtonDeleteTopicActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if(evt.WINDOW_GAINED_FOCUS != 1) {
            jTable1.setModel(new TopicTableModel());
        }
    }//GEN-LAST:event_formWindowGainedFocus

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteTopic;
    private javax.swing.JButton jButtonEditTopic;
    private javax.swing.JButton jButtonNewTopic;
    private javax.swing.JLabel jLabelTopic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
