/*
 * MeetingTypeSubGUI.java
 *
 * Created on 28. Dezember 2006, 01:04
 */

package todo.subgui;

import todo.core.MeetingType;
import todo.dbcon.DB_ToDo_Connect;
import java.sql.*;
/**
 *
 * @author  Gudrun
 */
public class MeetingTypeSubGUI extends javax.swing.JFrame {
    
    private static int status;              //0=Neu; 1=Bearbeiten
    private static String meetingType;     
    private static int meetingTypeID;      
    private MeetingType mt;          
    private Connection con;             

    /** Creates new form MeetingTypeSubGUI */
    public MeetingTypeSubGUI(int status, int meetingTypeID, String meetingType) {
        this.status = status;
        this.meetingTypeID = meetingTypeID;
        this.meetingType = meetingType;
        initComponents();
        if(status == 0) {
            //Neue Sitzungsart soll angelegt werden
            newMeetingTypeInit();
        }
        if(status == 1) {
            //Bestehende Sitzungsart soll bearbeitet werden
            editMeetingTypeInit();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSaveAndExit1 = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();
        jTextFieldMeetingType = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sitzungsarten verwalten");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSaveAndExit1.setText("Speichern und Schliessen");
        jButtonSaveAndExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAndExit1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSaveAndExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 230, 40));
        jPanel1.add(jTextFieldMeetingType, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 230, -1));

        jLabel3.setText("Sitzungsart");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 380, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveAndExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAndExit1ActionPerformed
        switch(status) {
            case 0:         // status=0, neue Tätigkeit anlegen
                newMeetingType();
                setVisible(false);
                break;
            case 1:         // status=1, vorhandene Tätigkeit bearbeiten
                editMeetingType();
                setVisible(false);
                break;
            default:
                jLabelError.setForeground(new java.awt.Color(255, 0, 0));
                jLabelError.setText("Fehler bei Ausführung des Befehls!");
        }
    }//GEN-LAST:event_jButtonSaveAndExit1ActionPerformed
    
    public void newMeetingTypeInit() {
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setText("Es müssen alle Felder ausgewählt werden");
    }
    
    public void editMeetingTypeInit() {
        jTextFieldMeetingType.setText(meetingType);
    }
    
    public void newMeetingType() {
        meetingType = jTextFieldMeetingType.getText();
        if(meetingType != "") {
            DB_ToDo_Connect dbCon = new DB_ToDo_Connect();
            dbCon.openDB();
            con = dbCon.getCon();
            try {
                Statement stmt = con.createStatement();
                String sql = "INSERT INTO Sitzungsart (Name) VALUES ('" + meetingType + "')";
                stmt.executeUpdate(sql);
                stmt.close();
            } catch(Exception e) {
                System.out.println(e.toString()); 
                System.exit(1);
            }
            dbCon.closeDB(con);
        }
        else {
            jLabelError.setText("Das Feld Sitzungsart muss ausgefüllt werden!");
        }    
    }
    
    public void editMeetingType() {
        meetingType = jTextFieldMeetingType.getText();
        if(meetingType != "") {
            DB_ToDo_Connect dbCon = new DB_ToDo_Connect();
            dbCon.openDB();
            con = dbCon.getCon();
        
            try {
                Statement stmt = con.createStatement();
                String sql = "UPDATE Sitzungsart SET Name='" + meetingType 
                            + "' WHERE SitzungsartID=" + meetingTypeID;
                    stmt.executeUpdate(sql);
                    stmt.close();
                } catch(Exception e) {
                    System.out.println(e.toString()); 
                    System.exit(1);
                }
                dbCon.closeDB(con);
            }
        else {
            jLabelError.setText("Das Feld Sitzungsart muss ausgefüllt werden!");
        }    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSaveAndExit1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldMeetingType;
    // End of variables declaration//GEN-END:variables
    
}
