/**
 * This file is part of 'Todo Application'
 * 
 * @see			http://www.konzept-e.de/
 * @copyright	2006-2011 Konzept-e für Bildung und Soziales GmbH
 * @author		Marcus Hertel, Sven Skrabal
 * @license		LGPL - http://www.gnu.org/licenses/lgpl.html
 * 
 */

package todo.dialog;

import todo.util.GlobalError;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import todo.entity.Employee;
import todo.db.DatabaseEmployeeConnect;
import todo.db.DatabaseTodoConnect;

public class TodoNoteDialog extends javax.swing.JDialog
{
	/** Creates new form TodoNoteSubGUI */
	public TodoNoteDialog(java.awt.Frame parent, boolean modal)
	{
		super(parent, modal);
		initComponents();

		ArrayList<Employee> allEmployees = getAllEmployees();
		for (int i = 0; i < allEmployees.size(); i++)
		{
			jComboBoxUser.addItem(allEmployees.get(i).getLastName() + ", " + allEmployees.get(i).getName());
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCalendarComboBoxDate = new de.wannawork.jcalendar.JCalendarComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxUser = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNote = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Notiz bzw. Bemerkung hinzufügen");
        setModal(true);
        setResizable(false);

        jLabel1.setText("Zeitpunkt der Erledigung:");

        jLabel2.setText("Erledigt von:");

        jLabel3.setText("Bemerkung bzw. Notiz:");

        jTextAreaNote.setColumns(20);
        jTextAreaNote.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNote);

        jButton1.setText("Speichern und schliessen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCalendarComboBoxDate, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCalendarComboBoxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
	{//GEN-HEADEREND:event_jButton1ActionPerformed
		if (jTextAreaNote.getText().equals(""))
		{
			JOptionPane.showMessageDialog(rootPane, "Das Feld für Bemerkungen bzw. Notizen muss ausgefüllt werden.");
			return;
		}

		dispose();
	}//GEN-LAST:event_jButton1ActionPerformed

	public String getNote()
	{
		return jTextAreaNote.getText();
	}

	public Date getDate()
	{
		return jCalendarComboBoxDate.getCalendar().getTime();
	}

	public String getUser()
	{
		return jComboBoxUser.getSelectedItem().toString();
	}

	private ArrayList getAllEmployees()
	{
		ArrayList<Employee> employeeObjects = new ArrayList<Employee>();
		DatabaseEmployeeConnect.openDB();
		Connection con = DatabaseEmployeeConnect.openDB();

		try
		{
			Statement stmt = con.createStatement();
			String sql = "SELECT * FROM Stammdaten ORDER BY Nachname ASC";
			ResultSet rst = stmt.executeQuery(sql);

			while (rst.next())
			{
				employeeObjects.add(new Employee((rst.getInt("Personalnummer")),
												 rst.getString("Vorname"), rst.getString("Nachname")));
			}
			rst.close();
			stmt.close();
		}
		catch (Exception ex)
		{
			Logger.getLogger(TodoNoteDialog.class.getName()).log(Level.SEVERE, null, ex);
			GlobalError.showErrorAndExit();
		}
		DatabaseEmployeeConnect.closeDB(con);
		return employeeObjects;
	}

	public static void showMemoPopup(int memoId)
	{
		DatabaseTodoConnect.openDB();
		Connection con = DatabaseTodoConnect.openDB();
		try
		{
			Statement stmt = con.createStatement();
			String sql = "SELECT * FROM Memo WHERE MemoID = " + memoId;
			ResultSet resultSet = stmt.executeQuery(sql);

			resultSet.next();

			String message = "Memo-Elemente dürfen per Definition nicht geändert werden und erscheinen daher lediglich als Nachricht!\n\n";
			message += "Für Nummer: " + resultSet.getInt("TodoID") + "\n";
			message += "Erstellt am: " + resultSet.getString("erstellt") + "\n";
			message += "Erstellt von: " + resultSet.getString("Benutzer") + "\n\n";
			message += "Inhalt:\n" + resultSet.getString("Inhalt");

			JOptionPane.showMessageDialog(null, message, "Memo-Inhalt", JOptionPane.INFORMATION_MESSAGE);

			resultSet.close();
			stmt.close();
		}
		catch (Exception ex)
		{
			Logger.getLogger(TodoNoteDialog.class.getName()).log(Level.SEVERE, null, ex);
			GlobalError.showErrorAndExit();
		}
		DatabaseTodoConnect.closeDB(con);
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBoxDate;
    private javax.swing.JComboBox jComboBoxUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaNote;
    // End of variables declaration//GEN-END:variables
}
