/*
 * FinStatusSubGUI.java
 *
 * Created on 29. Dezember 2006, 17:28
 */
package todo.subgui;

import todo.gui.GlobalError;
import todo.core.FinStatus;
import todo.dbcon.DB_ToDo_Connect;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  Gudrun
 */
public class FinStatusSubGUI extends javax.swing.JFrame
{
	private int status;              //0=Neu; 1=Bearbeiten
	private String statusName;
	private int statusID;
	private FinStatus fs;
	private static Connection con;

	/** Creates new form FinStatusSubGUI */
	public FinStatusSubGUI(int status, int statusID, String statusName)
	{
		this.status = status;
		this.statusID = statusID;
		this.statusName = statusName;
		initComponents();
		if (status == 0)
		{
			//Neuer Status soll angelegt werden
			newFinStatusInit();
		}
		if (status == 1)
		{
			//Bestehender Status soll bearbeitet werden
			editFinStatusInit();
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldStatusName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonSaveAndExit1 = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bearbeitungsstatus verwalten");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextFieldStatusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 230, -1));

        jLabel3.setText("Status");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 50, -1));

        jButtonSaveAndExit1.setText("Speichern und Schliessen");
        jButtonSaveAndExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAndExit1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSaveAndExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveAndExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAndExit1ActionPerformed
		switch (status)
		{
			case 0:         // status=0, neue Tätigkeit anlegen
				newFinStatus();
				setVisible(false);
				break;
			case 1:         // status=1, vorhandene Tätigkeit bearbeiten
				editFinStatus();
				setVisible(false);
				break;
			default:
				jLabelError.setForeground(new java.awt.Color(255, 0, 0));
				jLabelError.setText("Fehler bei Ausführung des Befehls!");
		}
    }//GEN-LAST:event_jButtonSaveAndExit1ActionPerformed

	public void newFinStatusInit()
	{
		jLabelError.setForeground(new java.awt.Color(255, 0, 0));
		jLabelError.setText("Es müssen alle Felder ausgewählt werden");
	}

	public void editFinStatusInit()
	{
		DB_ToDo_Connect.openDB();
		con = DB_ToDo_Connect.getCon();
		try
		{
			Statement stmt = con.createStatement();
			String sql = "SELECT * FROM Status WHERE StatusID = " + statusID;
			ResultSet resultSet = stmt.executeQuery(sql);

			resultSet.next();

			jTextFieldStatusName.setText(resultSet.getString("Name"));

			resultSet.close();
			stmt.close();
		}
		catch (Exception ex)
		{
			Logger.getLogger(AreaSubGUI.class.getName()).log(Level.SEVERE, null, ex);
			GlobalError.showErrorAndExit();
		}
		DB_ToDo_Connect.closeDB(con);
	}

	public void newFinStatus()
	{
		statusName = jTextFieldStatusName.getText();
		if (!statusName.equals(""))
		{
			DB_ToDo_Connect.openDB();
			con = DB_ToDo_Connect.getCon();
			try
			{
				Statement stmt = con.createStatement();
				String sql = "INSERT INTO Status (Name) VALUES ('" + statusName + "')";
				stmt.executeUpdate(sql);
				stmt.close();
			}
			catch (Exception ex)
			{
				Logger.getLogger(FinStatusSubGUI.class.getName()).log(Level.SEVERE, null, ex);
				GlobalError.showErrorAndExit();
			}
			DB_ToDo_Connect.closeDB(con);
		}
		else
		{
			jLabelError.setText("Das Feld Status muss ausgefüllt werden!");
		}
	}

	public void editFinStatus()
	{
		statusName = jTextFieldStatusName.getText();
		if (!statusName.equals(""))
		{
			DB_ToDo_Connect.openDB();
			con = DB_ToDo_Connect.getCon();

			try
			{
				Statement stmt = con.createStatement();
				String sql = "UPDATE Status SET Name='" + statusName + "' WHERE StatusID=" + statusID;
				stmt.executeUpdate(sql);
				stmt.close();
			}
			catch (Exception ex)
			{
				Logger.getLogger(FinStatusSubGUI.class.getName()).log(Level.SEVERE, null, ex);
				GlobalError.showErrorAndExit();
			}
			DB_ToDo_Connect.closeDB(con);
		}
		else
		{
			jLabelError.setText("Das Feld Status muss ausgefüllt werden!");
		}
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSaveAndExit1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldStatusName;
    // End of variables declaration//GEN-END:variables
}
