/*
 * InstitutionSubGUI.java
 *
 * Created on 29. Dezember 2006, 18:24
 */
package todo.subgui;

import todo.gui.GlobalError;
import todo.core.Institution;
import todo.dbcon.DB_ToDo_Connect;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  Marcus Hertel
 */
public class InstitutionSubGUI extends javax.swing.JFrame
{

	private int status;              //0=Neu; 1=Bearbeiten
	private String institution;
	private int institutionID;
	private Institution inst;
	private static Connection con;

	/** Creates new form InstitutionSubGUI */
	public InstitutionSubGUI(int status, int institutionID, String institution)
	{
		this.status = status;
		this.institutionID = institutionID;
		this.institution = institution;
		initComponents();
		if (status == 0)
		{
			//Neue Institution soll angelegt werden
			newInstitutionInit();
		}
		if (status == 1)
		{
			//Bestehende Institution soll bearbeitet werden
			editInstitutionInit();
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSaveAndExit1 = new javax.swing.JButton();
        jTextFieldInstitution = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Institutionen verwalten");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(340, 120));
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 120));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSaveAndExit1.setText("Speichern und Schliessen");
        jButtonSaveAndExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAndExit1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSaveAndExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));
        jPanel1.add(jTextFieldInstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 230, -1));

        jLabel3.setText("Institution");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, -1));

        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveAndExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAndExit1ActionPerformed
		switch (status)
		{
			case 0:         // status=0, neue Institution anlegen
				newInstitution();
				setVisible(false);
				break;
			case 1:         // status=1, vorhandene Institution bearbeiten
				editInstitution();
				setVisible(false);
				break;
			default:
				jLabelError.setForeground(new java.awt.Color(255, 0, 0));
				jLabelError.setText("Fehler bei Ausführung des Befehls!");
		}
    }//GEN-LAST:event_jButtonSaveAndExit1ActionPerformed

	public void newInstitutionInit()
	{
		jLabelError.setForeground(new java.awt.Color(255, 0, 0));
		jLabelError.setText("Es müssen alle Felder ausgewählt werden");
	}

	public void editInstitutionInit()
	{
		jTextFieldInstitution.setText(institution);
	}

	public void newInstitution()
	{
		institution = jTextFieldInstitution.getText();
		if (!institution.equals(""))
		{
			DB_ToDo_Connect.openDB();
			con = DB_ToDo_Connect.getCon();
			try
			{
				Statement stmt = con.createStatement();
				String sql = "INSERT INTO Institution (Name) VALUES ('" + institution + "')";
				stmt.executeUpdate(sql);
				stmt.close();
			} catch (Exception ex)
			{
				Logger.getLogger(InstitutionSubGUI.class.getName()).log(Level.SEVERE, null, ex);
				GlobalError.showErrorAndExit();
			}
			DB_ToDo_Connect.closeDB(con);
		}
		else
		{
			jLabelError.setText("Das Feld Institution muss ausgefüllt werden!");
		}
	}

	public void editInstitution()
	{
		institution = jTextFieldInstitution.getText();
		if (!institution.equals(""))
		{
			DB_ToDo_Connect.openDB();
			con = DB_ToDo_Connect.getCon();

			try
			{
				Statement stmt = con.createStatement();
				String sql = "UPDATE Institution SET Name='" + institution + "' WHERE InstitutionID=" + institutionID;
				stmt.executeUpdate(sql);
				stmt.close();
			} catch (Exception ex)
			{
				Logger.getLogger(InstitutionSubGUI.class.getName()).log(Level.SEVERE, null, ex);
				GlobalError.showErrorAndExit();
			}
			DB_ToDo_Connect.closeDB(con);
		}
		else
		{
			jLabelError.setText("Das Feld Institution muss ausgefüllt werden!");
		}
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSaveAndExit1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldInstitution;
    // End of variables declaration//GEN-END:variables
}
