/*
 * MeetingSubGUI.java
 *
 * Created on 6. Januar 2007, 17:14
 */
package todo.subgui;

import todo.gui.GlobalError;
import todo.core.Employee;
import todo.core.Meeting;
import todo.core.MeetingType;
import todo.dbcon.DB_ToDo_Connect;
import todo.dbcon.DB_Mitarbeiter_Connect;
import todo.gui.MeetingTypeGUI;
import todo.gui.ParticipantsGUI;
import java.sql.*;
import java.util.*;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author  Marcus Hertel
 */
public class MeetingSubGUI extends javax.swing.JFrame
{
	private int status = 0;
	private int meetingID;
	private String meetingType;
	private String date;
	private String otherPart;
	private Meeting meet = new Meeting();
	private static Connection con;
	private static Connection con2;
	private ArrayList<Integer> participants = new ArrayList<Integer>();
	private Calendar cal = Calendar.getInstance();
	private boolean reDateChange = false;
	private boolean flagParticipants = false;  //true, falls Teilnehmer hinzugefügt wurden
	// und somit schon Sitzung angelegt wurde.

	/**
	 * Creates new form MeetingSubGUI
	 */
	public MeetingSubGUI()
	{
		initComponents();
	}

	public MeetingSubGUI(int status, int meetingID, String meetingType,
						 String date, String otherPart)
	{
		this.status = status;
		this.meetingID = meetingID;
		this.meetingType = meetingType;
		this.date = date;
		this.otherPart = otherPart;
		initComponents();
		if (status == 0)
		{
			//neue Sitzung anlegen
			newMeetingInit();
		}
		if (status == 1)
		{
			//vorhandene Sitzung bearbeiten
			editMeetingInit();
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxMeetingType = new javax.swing.JComboBox();
        jButtonMeetingType = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPlace = new javax.swing.JTextField();
        jComboBoxProt = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButtonParticipants = new javax.swing.JButton();
        jButtonSaveAndExit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCalendarComboBoxDate = new de.wannawork.jcalendar.JCalendarComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sitzung verwalten");
        setMinimumSize(new java.awt.Dimension(480, 210));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Datum");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, -1));
        getContentPane().add(jComboBoxMeetingType, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 250, -1));

        jButtonMeetingType.setText("Sitzungsarten...");
        jButtonMeetingType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeetingTypeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMeetingType, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 120, -1));

        jLabel2.setText("Ort");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        getContentPane().add(jTextFieldPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, -1));
        getContentPane().add(jComboBoxProt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 220, -1));

        jLabel4.setText("Protokollant");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, -1));

        jButtonParticipants.setText("Teilnehmer verwalten");
        jButtonParticipants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParticipantsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonParticipants, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 160, -1));

        jButtonSaveAndExit.setText("Speichern und schliessen");
        jButtonSaveAndExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAndExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSaveAndExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jButton1.setText("Mitarbeiter verwalten");
        jButton1.setEnabled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 140, -1));

        jCalendarComboBoxDate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCalendarComboBoxDateStateChanged(evt);
            }
        });
        getContentPane().add(jCalendarComboBoxDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 140, 20));

        jLabel3.setText(" ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * öffnet ParticipantsGUI um Teilnehmer zu bearbeiten
	 *
	 * @param evt
	 */
    private void jButtonParticipantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParticipantsActionPerformed
		// aktualisiere Daten der Sitzung vor Öffnen von ParticipantsGUI
		refreshMeetingData();
		if (meetingID == 0)
		{
			newMeeting();
			getMeetingID();
			flagParticipants = true;
		}
		ParticipantsGUI partGUI = new ParticipantsGUI(participants, otherPart, meetingID);
		partGUI.setVisible(true);
    }//GEN-LAST:event_jButtonParticipantsActionPerformed

    private void jButtonSaveAndExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAndExitActionPerformed
		switch (status)
		{
			case 0:         // status=0, neue Sitzung anlegen
				if (flagParticipants)
				{   //Sitzung ist schon angelegt
					getMeetingID();
					editMeeting();
					setVisible(false);
					break;
				}
				else
				{
					newMeeting();
					setVisible(false);
					break;
				}
			case 1:         // status=1, vorhandene Sitzung bearbeiten
				editMeeting();
				setVisible(false);
				break;
			default:
				JOptionPane.showMessageDialog(rootPane, "Fehler bei Ausführung des Befehls!");
		}
    }//GEN-LAST:event_jButtonSaveAndExitActionPerformed

    private void jButtonMeetingTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeetingTypeActionPerformed
		//MeetingTypeGUI öffnen um Sitzungsarten zu bearbeiten
		MeetingTypeGUI meetType = new MeetingTypeGUI();
		meetType.setVisible(true);
    }//GEN-LAST:event_jButtonMeetingTypeActionPerformed

    private void jCalendarComboBoxDateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCalendarComboBoxDateStateChanged
		if (evt.getSource() == jCalendarComboBoxDate)
		{
			cal.set(jCalendarComboBoxDate.getCalendar().get(Calendar.YEAR),
					jCalendarComboBoxDate.getCalendar().get(Calendar.MONTH) + 1,
					jCalendarComboBoxDate.getCalendar().get(Calendar.DAY_OF_MONTH));
			reDateChange = true;
		}
}//GEN-LAST:event_jCalendarComboBoxDateStateChanged

	public void newMeetingInit()
	{
		jComboBoxMeetingType.addItem("Bitte wählen...");
		jComboBoxProt.addItem("Bitte wählen...");
		ArrayList<MeetingType> mt = getAllMeetingTypes();
		ArrayList<Employee> emp = getAllEmployees();
		for (int i = 0; i < mt.size(); i++)
		{
			jComboBoxMeetingType.addItem(mt.get(i).getMeetingType());
		}
		for (int i = 0; i < emp.size(); i++)
		{
			jComboBoxProt.addItem(emp.get(i).getLastName() + ", " + emp.get(i).getName());
		}
	}

	/**
	 * Alle Benötigten Daten zum Bearbeiten der bereits vorhandenen Sitzung
	 * werden geladen
	 */
	public void editMeetingInit()
	{
		ArrayList<MeetingType> mt = getAllMeetingTypes();
		ArrayList<Employee> emp = getAllEmployees();
		for (int i = 0; i < mt.size(); i++)
		{
			jComboBoxMeetingType.addItem(mt.get(i).getMeetingType());
		}
		for (int i = 0; i < emp.size(); i++)
		{
			jComboBoxProt.addItem(emp.get(i).getLastName() + ", " + emp.get(i).getName());
		}
		refreshMeetingData();
		cal.setTime(meet.getDate());
		jCalendarComboBoxDate.setCalendar(cal);
		jTextFieldPlace.setText(meet.getPlace());
		jComboBoxProt.setSelectedItem(getNameOfProt(meet.getProt()));
		jComboBoxMeetingType.setSelectedItem(meet.getMeetingType());
	}

	/*
	 *
	 */
	public void newMeeting()
	{
		meet.setDate(jCalendarComboBoxDate.getCalendar().getTime());
		meet.setMeetingType(String.valueOf(jComboBoxMeetingType.getSelectedItem()));
		meet.setMeetingTypeID(getMeetingTypeIDByName(meet.getMeetingType()));
		meet.setPlace(jTextFieldPlace.getText());
		if (!String.valueOf(jComboBoxProt.getSelectedItem()).equals("Bitte wählen..."))
		{
			meet.setProt(getProtIDByName(String.valueOf(jComboBoxProt.getSelectedItem())));
		}
		else
		{
			meet.setProt(1);
		}
		
		if (!meet.getMeetingType().equals(""))
		{
			DB_ToDo_Connect.openDB();
			con = DB_ToDo_Connect.getCon();
			try
			{
				Statement stmt = con.createStatement();
				//Verantwortliche
				java.sql.Date dat = new java.sql.Date(meet.getDate().getTime());
				String sql = "INSERT INTO Sitzungsdaten (Datum, SitzungsartID, "
							 + "Ort, Protokollant, Geloescht) VALUES ('" + dat + "', "
							 + meet.getMeetingTypeID() + ", '" + meet.getPlace() + "', '"
							 + meet.getProt() + "', false)";
				stmt.executeUpdate(sql);
				stmt.close();
			}
			catch (Exception ex)
			{
				Logger.getLogger(MeetingSubGUI.class.getName()).log(Level.SEVERE, null, ex);
				GlobalError.showErrorAndExit();
			}
			DB_ToDo_Connect.closeDB(con);
		}
		else
		{
			JOptionPane.showMessageDialog(rootPane, "Die Felder Datum, Sitzungsart und Ort müssen ausgefüllt werden!");
		}
	}

	/**
	 * - Änderung von Daten einer Sitzung -
	 * Alle angegebenen Daten der bereits vorhandenen Sitzung werden in die
	 * Tabelle Sitzungsdaten der Datenbank hinterlegt
	 */
	public void editMeeting()
	{
		meet.setDate(jCalendarComboBoxDate.getCalendar().getTime());
		meet.setMeetingType(String.valueOf(jComboBoxMeetingType.getSelectedItem()));
		meet.setMeetingTypeID(getMeetingTypeIDByName(meet.getMeetingType()));
		meet.setPlace(jTextFieldPlace.getText());
		if (!String.valueOf(jComboBoxProt.getSelectedItem()).equals("Bitte wählen..."))
		{
			meet.setProt(getProtIDByName(String.valueOf(jComboBoxProt.getSelectedItem())));
		}
		else
		{
			meet.setProt(1);
		}
		
		if (!meet.getMeetingType().equals(""))
		{
			DB_ToDo_Connect.openDB();
			con = DB_ToDo_Connect.getCon();
			try
			{
				Statement stmt = con.createStatement();
				//Verantwortliche
				java.sql.Date dat = new java.sql.Date(meet.getDate().getTime());
				String sql = "UPDATE Sitzungsdaten SET Datum = '" + dat + "', SitzungsartID = " + meet.getMeetingTypeID() + ", Ort = '" + meet.getPlace() + "', Protokollant = " + meet.getProt() + " WHERE SitzungsdatenID = " + meetingID;
				stmt.executeUpdate(sql);
				stmt.close();
			}
			catch (Exception ex)
			{
				Logger.getLogger(MeetingSubGUI.class.getName()).log(Level.SEVERE, null, ex);
				GlobalError.showErrorAndExit();
			}
			DB_ToDo_Connect.closeDB(con);
		}
		else
		{
			JOptionPane.showMessageDialog(rootPane, "Die Felder Datum, Sitzungsart und Ort müssen ausgefüllt werden!");
		}
	}

	/*
	 * ermittelt den Namen des Protokollanten bezüglich dessen ID
	 */
	public String getNameOfProt(int protID)
	{
		String protName = "";
		DB_Mitarbeiter_Connect.openDB();
		con2 = DB_Mitarbeiter_Connect.getCon();

		try
		{
			Statement stmt = con2.createStatement();
			String sql = "SELECT * FROM Stammdaten WHERE Personalnummer = " + protID;
			ResultSet rst = stmt.executeQuery(sql);

			while (rst.next())
			{
				protName = rst.getString("Nachname") + ", " + rst.getString("Vorname");
			}
			rst.close();
			stmt.close();
		}
		catch (Exception ex)
		{
			Logger.getLogger(MeetingSubGUI.class.getName()).log(Level.SEVERE, null, ex);
			GlobalError.showErrorAndExit();
		}
		DB_ToDo_Connect.closeDB(con);
		return protName;
	}

	/*
	 *  ermittelt die Namen aller Mitarbeiter zur Auswahl des Protokollanten
	 */
	public ArrayList getAllEmployees()
	{
		ArrayList<Employee> employeeObjects = new ArrayList<Employee>();
		DB_Mitarbeiter_Connect.openDB();
		con = DB_Mitarbeiter_Connect.getCon();

		try
		{
			Statement stmt = con.createStatement();
			String sql = "SELECT * FROM Stammdaten ORDER BY Nachname ASC";
			ResultSet rst = stmt.executeQuery(sql);

			while (rst.next())
			{
				employeeObjects.add(new Employee((rst.getInt("Personalnummer")),
												 rst.getString("Vorname"), rst.getString("Nachname")));
			}
			rst.close();
			stmt.close();
		}
		catch (Exception ex)
		{
			Logger.getLogger(MeetingSubGUI.class.getName()).log(Level.SEVERE, null, ex);
			GlobalError.showErrorAndExit();
		}
		DB_ToDo_Connect.closeDB(con);
		return employeeObjects;
	}

	/*
	 * ermittlet alle Sitzungsartenobjekte zur Auswahl
	 */
	public ArrayList getAllMeetingTypes()
	{
		ArrayList<MeetingType> meetingTypeObjects = new ArrayList<MeetingType>();
		DB_ToDo_Connect.openDB();
		con = DB_ToDo_Connect.getCon();

		try
		{
			Statement stmt = con.createStatement();
			String sql = "SELECT * FROM Sitzungsart ORDER BY Name ASC";
			ResultSet rst = stmt.executeQuery(sql);

			while (rst.next())
			{
				meetingTypeObjects.add(new MeetingType(rst.getInt("SitzungsartID"),
													   rst.getString("Name")));
			}
			rst.close();
			stmt.close();
		}
		catch (Exception ex)
		{
			Logger.getLogger(MeetingSubGUI.class.getName()).log(Level.SEVERE, null, ex);
			GlobalError.showErrorAndExit();
		}
		DB_ToDo_Connect.closeDB(con);
		return meetingTypeObjects;
	}

	public void getMeetingData()
	{
		DB_ToDo_Connect.openDB();
		con = DB_ToDo_Connect.getCon();

		try
		{
			Statement stmt = con.createStatement();
			String sql = "SELECT * FROM Sitzungsdaten WHERE SitzungsdatenID = " + meetingID;
			ResultSet rst = stmt.executeQuery(sql);

			while (rst.next())
			{
				meet.setDate(rst.getDate("Datum"));
				meet.setPlace(rst.getString("Ort"));
				meet.setProt(rst.getInt("Protokollant"));
				meet.setOtherParticipants(rst.getString("Sonstige"));
				int meetingTypeID = rst.getInt("SitzungsartID");
				meet.setMeetingTypeID(meetingTypeID);
				String meetingType = "";
				Statement stmt2 = con.createStatement();
				String sql2 = "SELECT * FROM Sitzungsart WHERE SitzungsartID = "
							  + meetingTypeID;
				ResultSet rst2 = stmt2.executeQuery(sql2);

				while (rst2.next())
				{
					meet.setMeetingType(rst2.getString("Name"));
				}
				rst2.close();
				stmt2.close();

			}
			rst.close();
			stmt.close();
		}
		catch (Exception ex)
		{
			Logger.getLogger(MeetingSubGUI.class.getName()).log(Level.SEVERE, null, ex);
			GlobalError.showErrorAndExit();
		}
		DB_ToDo_Connect.closeDB(con);
	}

	public int getMeetingTypeIDByName(String meetingType)
	{
		int mtID = 0;
		DB_ToDo_Connect.openDB();
		con = DB_ToDo_Connect.getCon();

		try
		{
			Statement stmt = con.createStatement();
			String sql = "SELECT * FROM Sitzungsart WHERE Name = '" + meet.getMeetingType() + "'";
			ResultSet rst = stmt.executeQuery(sql);

			while (rst.next())
			{
				mtID = rst.getInt("SitzungsartID");
			}
			rst.close();
			stmt.close();
		}
		catch (Exception ex)
		{
			Logger.getLogger(MeetingSubGUI.class.getName()).log(Level.SEVERE, null, ex);
			GlobalError.showErrorAndExit();
		}
		DB_ToDo_Connect.closeDB(con);
		return mtID;
	}

	public int getProtIDByName(String protName)
	{
		int prID = 0;
		DB_Mitarbeiter_Connect.openDB();
		con = DB_Mitarbeiter_Connect.getCon();

		String name = "";
		String lastName = "";

		String splitName[] = protName.split(",");
		lastName = splitName[0].trim();
		name = splitName[1].trim();

		try
		{
			Statement stmt = con.createStatement();
			String sql = "SELECT * FROM Stammdaten WHERE Vorname = '" + name + "' AND Nachname = '" + lastName + "'";
			ResultSet rst = stmt.executeQuery(sql);

			while (rst.next())
			{
				prID = rst.getInt("Personalnummer");
			}
			rst.close();
			stmt.close();
		}
		catch (Exception ex)
		{
			Logger.getLogger(MeetingSubGUI.class.getName()).log(Level.SEVERE, null, ex);
			GlobalError.showErrorAndExit();
		}
		DB_ToDo_Connect.closeDB(con);
		return prID;
	}

	public void getAllParticipants()
	{
		// Vektor participants komplett leeren
		participants.clear();

		DB_ToDo_Connect.openDB();
		con = DB_ToDo_Connect.getCon();

		try
		{
			Statement stmt = con.createStatement();
			String sql = "SELECT personnelID FROM meeting_attendee_personnel WHERE meetingID = " + meetingID;
			ResultSet rst = stmt.executeQuery(sql);

			while (rst.next())
			{
				participants.add(rst.getInt("personnelID"));
			}

			rst.close();
			stmt.close();
		}
		catch (Exception ex)
		{
			Logger.getLogger(MeetingSubGUI.class.getName()).log(Level.SEVERE, null, ex);
			GlobalError.showErrorAndExit();
		}
		
		DB_ToDo_Connect.closeDB(con);
	}

	public void getMeetingID()
	{
		int mID = 0;
		DB_ToDo_Connect.openDB();
		con = DB_ToDo_Connect.getCon();

		try
		{
			Statement stmt = con.createStatement();
			String sql = "SELECT * FROM Sitzungsdaten ORDER BY SitzungsdatenID ASC";
			ResultSet rst = stmt.executeQuery(sql);

			while (rst.next())
			{
				mID = rst.getInt("SitzungsdatenID");
			}
			rst.close();
			stmt.close();
		}
		catch (Exception ex)
		{
			Logger.getLogger(MeetingSubGUI.class.getName()).log(Level.SEVERE, null, ex);
			GlobalError.showErrorAndExit();
		}
		DB_ToDo_Connect.closeDB(con);
		meetingID = mID;
	}

	/**
	 * Aktualisierung der Daten einer Sitzung aus der Datenbank
	 * !notwendig da nach dem Schliessen von ParticipantsGUI sonst bei
	 * erneutem Aufrufen der Maske über "Teilnehmer verwalten", alte Daten
	 * angezeigt werden würden
	 */
	public void refreshMeetingData()
	{
		getMeetingData();
		otherPart = meet.getOtherPaticipants();
		getAllParticipants();
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonMeetingType;
    private javax.swing.JButton jButtonParticipants;
    private javax.swing.JButton jButtonSaveAndExit;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBoxDate;
    private javax.swing.JComboBox jComboBoxMeetingType;
    private javax.swing.JComboBox jComboBoxProt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldPlace;
    // End of variables declaration//GEN-END:variables
}
